### ISSUE TITLE
ValidUntil can't be removed from the metadata EntityDescriptor tag

### ISSUE THREAD

**Issue by macmon-secure** [onelogin/java-saml#106]
The validUntilTime will always be set in the metadata in the EntityDescriptor tag. 
The Metadata class constructor uses the constant N_DAYS_VALID_UNTIL, when the validUntilTime is null.
Wouldn't it be better that when the time is null, it won't be inserted in the metadata file and only and only when validUntilTime isn't null? Is this common best practice or is there another possibility to set the validUntilTime to something like "always"?

**Comment by pitbulk** [comment]
You can put a far away date and that will solve any expiration issue... but take in mind that metadata used to change... change endpoints, new certs... I don't see any problem with the need of require just a date.

**Comment by laurentleseigneur** [comment]
Hi all,

I have the same issue, and according to schema http://docs.oasis-open.org/security/saml/v2.0/saml-schema-metadata-2.0.xsd, those attributes are defined `optional`, so if i din't need to manage those attributes, i'd like to remove then from xml file, that's still valid

will provide a PR for that, since i need to exclude those attribute when they are set to null which is not possible while reading https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/settings/Metadata.java#L78
