### ISSUE TITLE
Send encryption keys only when required

### ISSUE THREAD

**Issue by pitbulk** [onelogin/java-saml#119]
As @waynewoodfield  required on #117 we may avoid publish metadata with encryption keys if they are not required. Some IdPs encrypt automatically assertions when SP publish encryption keys, and we don't want that behavior.

**Comment by waynewoodfield** [comment]
I've updated fork waynewoodfield:conditional-certs to include recommendations by Sixto - the signing key is published unconditionally, and encryption key will still be sent when getWantNameIdEncrypted is true.  If you'd like to use that fork, I can resubmit a pull request.  Otherwise, looking forward to your updates.
