### ISSUE TITLE
Change Name of the attribute that is used as NameID

### ISSUE THREAD

**Issue by sreeharibs** [onelogin/java-saml#129]
_First of all Sorry , if the question already have an answer._

 My Idp requires me to use `uid` instead of `NameID` as `Name of the attribute that is used as NameID`

How can I achieve this one.

Thanks

**Comment by pitbulk** [comment]
Is uid an Attribute that gonna be included inside an AttributeStatement element?

Then you only need to use the [getAttribute](https://github.com/onelogin/java-saml/blob/master/toolkit/src/main/java/com/onelogin/saml2/Auth.java#L685) method to retrieve that value.
```
getAttribute('uid')
```
Otherwise maybe the uid is provided in the NameId element, but you may use a different NameID Format than 'emailAddress'
