### ISSUE TITLE
Support multiple certificates for IdP

### ISSUE THREAD

**Issue by veselov** [onelogin/java-saml#150]
I'm using Onelogin library (2.2.0) in our SP. One of our customers is using SAML from Azure. Apparently, SAML responses can be signed with various certificates. They are of the same issuer, but certificates are different. I've seen at least two. But I don't know how many there are.
AFAIU, one has to provide list of certs or cert hashes, otherwise it's a security problem, as long as certs are mostly self-signed. So I have to get them all.
I see there is a statement about multiple IdP certificates in README.md, but I can't find reference to `onelogin.saml2.idp.x509certMulti` parameter in the source code (Saml2Settings). Also, the verification code just gets the cert/fingerprint info from the settings object, and passes it to `Util.validateSign()`.
Considering that Azure uses multiple certs, it seems like a necessary feature to have for integration. I have to implement this rather quickly, I wonder if you guys can provide any pointers, and whether you are interested in a merge request.

Thank you.

**Comment by pitbulk** [comment]
>  Apparently, SAML responses can be signed with various certificates. 
That sentence is not correct at all

The use of multiple certs is just a temporal state when SAML entity is performing a cert rollover (switching from 1 cert to another). For example, when IdP need to use a new pair of private key/public cert, the SP temporarily will have the old public cert and the new public cert, and in the validation process, the SP will use both in order to try validate the signature. Similar happens when SP want to use a new pair of private key/public cert, that IdP will register both of them and is what you see on the Azure.

The [x509certMulti](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L298) is available in the master branch. Not yet available in an official release.
 
So please, try to use the code available in master branch and let me know if you experience any issue.

**Comment by veselov** [comment]
Can you please point me to the SAML documentation block that states that using multiple certificates is not correct? I'm seeing these two distinct certificates used by MS/Azure, and they do not look like they are for key rollover. At least I'd expect that to happen close to cert expiry date.

1. https://pastebin.com/21dQv3zh
1. https://pastebin.com/wZ3QYUtw

**Comment by pitbulk** [comment]
Azure (or any SAML Entity) could be able to:
- Has registered 2 private key/public cert in order to sign the SAML messages (that is common during a cert rollover scenario), so 2 public certificates will be included on the IdP metadata. Is also possible that IdP is connected with multiple SPs, and IdP use different private key/public cert per SP, so IdP metadata will provide all of them ... but think that at the end, only 1 private key will be used to sign a SAML Message .. so the IdP will always follow some rule to determine what private key and use always the same for a specific SP.
- Has registered 2 public certificates of a SP (that is common during a cert rollover scenario), in order to be able to validate the signature of the SAMLResponse sent by the SP without "cut the service" due the action of switch the private key/certificate on the SP.

References:
- https://www.switch.ch/aai/guides/idp/certificate-rollover/
- https://docs.microsoft.com/en-us/azure/active-directory/connect/active-directory-aadconnect-o365-certs

P.S I have some pending commits, after them I think can release the new version.

**Comment by veselov** [comment]
I'll try to get the #149 in there then.

Thanks for the links. I meant something from the SAML spec that says "you must use one cert only".

What is the recommended practice for dealing with this as the user of the library? We are not dealing with the second case, because we are the SP, and we didn't give them a new cert. I'm sceptical that this is a rollover, because both certs have been issued well in the past (Jan or Feb), and have plenty of time to go (till 2020). Is there a tool or a library to process the federation metadata, and update the certificates to be used for SAML?

I did check their federation data, and I see 3 certificates being listed there. All with signing KU. Which one should I consider as "main"? The one they used to sign the federation metadata itself?

Thank you!

**Comment by pitbulk** [comment]
The main should be the first.

**Comment by sfodje** [comment]
> The main should be the first.

This isn't always true. I have to support some widely used Identity Providers that use the first certificate marked with <EntityDescriptor use="signing"> and others that require the first certificate in the metadata. 
From what I can see from the source code the additional sp certificates aren't being used at all. It would be nice to validate against all the provided certificates.
