### ISSUE TITLE
LogoutRequest returns StatusCode Requester instead of Success

### ISSUE THREAD

**Issue by clementlefevre** [onelogin/java-saml#154]
First of all, thanks a lot for all the contributors of this library that makes the Saml process much easier.

Using the onelogin sample app as SP  with sso circle as IdP,  **login via SSOCircle IdP works**, but the **LogoutRequest**, after being validated, returns a LogOutResponse with **StatusCode** _Requester_ instead of _Success_ : 
```
<samlp:LogoutResponse  xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
ID="sc542bf9722770985152c9161dd5ebae24df3dcc7" Version="2.0" IssueInstant="2018-03-28T07:50:49Z" Destination="http://localhost:8080/onelogin-saml/sls.jsp" InResponseTo="ONELOGIN_eb7e1704-b265-48b9-a7e3-6fd3f26b4a0e">
<saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://idp.ssocircle.com</saml:Issuer>
<samlp:Status xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
<samlp:StatusCode xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Value="urn:oasis:names:tc:SAML:2.0:status:Requester">
</samlp:StatusCode>
</samlp:Status>
</samlp:LogoutResponse>
```
IdP initiated Logout **works**.

I cannot figure out what am i missing in the properties configuration :

```
onelogin.saml2.sp.single_logout_service.url=http://localhost:8080/onelogin-saml/sls.jsp
onelogin.saml2.sp.single_logout_service.binding=urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
onelogin.saml2.sp.nameidformat=urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
onelogin.saml2.idp.single_logout_service.url=https://idp.ssocircle.com:443/sso/IDPSloRedirect/metaAlias/publicidp
onelogin.saml2.idp.single_logout_service.response.url=
onelogin.saml2.idp.single_logout_service.binding=urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
```

Any input would be warmly welcome.

**Comment by pitbulk** [comment]
I think SSO Circle rejects SLO Request because it expects to contain info about NameID, NameiDFormat and SessionIndex.
The demo example was kinda simple and does not handle that data,
Please expand demo example and:
1. On [ACS view](https://github.com/onelogin/java-saml/blob/master/samples/java-saml-tookit-jspsample/src/main/webapp/acs.jsp) store info about NameID, NameiDFormat and SessionIndex on the session.
2. On [Logout view](https://github.com/onelogin/java-saml/blob/master/samples/java-saml-tookit-jspsample/src/main/webapp/dologout.jsp) extend the logout method providing NameID, NameiDFormat and SessionIndex data.

Reference: See [PHP demo](https://github.com/onelogin/php-saml/blob/master/demo1/index.php)

P.S If you want to provide a PR to add this support, it is welcome.

**Comment by clementlefevre** [comment]
Again, **many thanks for your reactivity and efficience.** 

The wall i was banging my head into is having well-deserved break.

For those interested, i implemented the solution of Martin as follow in the sample app : 

- in **acs.jsp** : 

```
session.setAttribute("nameId", nameId);
session.setAttribute("sessionId", sessionIndex);
session.setAttribute("nameIdFormat", nameIdFormat);
```

and the in **dologout.jsp** :

```
Auth auth = new Auth(request, response);
auth.logout(null, session.getAttribute("nameId").toString(),
session.getAttribute("sessionId").toString(),
session.getAttribute("nameIdFormat").toString());
```


And the ssocircle logoutResponse is now a (great) success.
