### ISSUE TITLE
Decrypt SAML data

### ISSUE THREAD

**Issue by ravisg** [onelogin/java-saml#164]
I have an encrypted SAML data coming into my application , I would like to convert it into a base64 encoded object , decode it and decrypt the result using my private key . How would I be doing that programmatically when I have File objects to my public key , private key and encrypted data .

I see your online tool does it for me :https://www.samltool.com/online_tools.php . I would like to do the same programatically .

**Comment by pitbulk** [comment]
The [base64decodedInflated](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/util/Util.java#L658) is able to get the base64Deflatedencoded version of the SAMLMessage and obtain the XML string.

The [loadXML](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/util/Util.java#L154) method convert the xml string on a Document.

The [decryptAssertion](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L1069) decrypts the encrypted assertion.

You can review the code of the toolkit in order to build the process you need.

**Comment by ravisg** [comment]
Thanks @pitbulk  for the quick response , I used the base64decodedInflated method on a SAMLMessage but it throws the below exception . I don't see the ReadablePeriod classa anywhere, are there any missing files in the git repo ? 

 `Exception in thread "main" java.lang.NoClassDefFoundError: org/joda/time/ReadablePeriod
	at convertSAML.main(convertSAML.java:41)
Caused by: java.lang.ClassNotFoundException: org.joda.time.ReadablePeriod
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more`

**Comment by pitbulk** [comment]
org/joda/time/ReadablePeriod belong to the joda-time library defined on the [pom.xml](https://github.com/onelogin/java-saml/blob/master/core/pom.xml#L49)

**Comment by ravisg** [comment]
I also tried to add a maven shade plugin and do an [uber build](http://www.avajava.com/tutorials/lessons/how-do-i-build-a-jar-file-that-contains-its-dependencies.html?page=1) . It still wouldnt get all the dependencies
