### ISSUE TITLE
Invalid settings: idp_cert_or_fingerprint_not_found_and_required (dologin.jsp)

### ISSUE THREAD

**Issue by gregigorius** [onelogin/java-saml#176]
org.apache.jasper.JasperException: An exception occurred processing JSP page [/dologin.jsp] at line [10]

7: </head>
8: <body>
9: 	<%
10: 		Auth auth = new Auth(request, response);
11: 		if (request.getParameter("attrs") == null) {
12: 			auth.login();
13: 		} else {

Stacktrace:
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:584)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Root Cause

javax.servlet.ServletException: com.onelogin.saml2.exception.SettingsException: Invalid settings: idp_cert_or_fingerprint_not_found_and_required
	org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:909)
	org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:838)
	org.apache.jsp.dologin_jsp._jspService(dologin_jsp.java:142)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Root Cause

com.onelogin.saml2.exception.SettingsException: Invalid settings: idp_cert_or_fingerprint_not_found_and_required
	com.onelogin.saml2.Auth.<init>(Auth.java:224)
	com.onelogin.saml2.Auth.<init>(Auth.java:180)
	org.apache.jsp.dologin_jsp._jspService(dologin_jsp.java:120)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by pitbulk** [comment]
That happens when you have not provided IdP public certificate or its fingerprint on the settings, so the toolkit is not able to validate the SAMLResponse.

**Comment by jaikiran** [comment]
I would like to add an input here. We kept running into this same error message when trying out the library for the first time. What was happening was, although in our .properties file (the one which was being read to build the settings), we had specified the value for the x509cert property, the value of the property wasn't well-escaped. The x509 cert value is a multi-line value which means the end of each line in the value, needs to be escaped by a `\\n` (except the last line of the value). Not doing so, ends up in the library reading this value and trying to parse the value as a x509 cert using the internal `Util` class. It runs into an error due to the invalid content and ends up just logging that issue and then throwing this error message. 

Perhaps the library can be enhanced to use a different error message if the parsing of this value itself fails. But for now, you can checkout your server log files which should contain the log messages/exception stacktrace which I think would show the certificate loading is failing.

**Comment by workprotocol** [comment]
Agreed with Jaikiran, this has to do with the multi-line value of x509 certificate when passing to .properties file. Solution is simple:  Use any online/offline tool to make it one liner by removing all line breaks.

**Comment by pitbulk** [comment]
Like:
- https://www.samltool.com/format_x509cert.php
- https://www.samltool.com/format_privatekey.php
