### ISSUE TITLE
Add support to pass Destination validation if it has query string in URL so that SP could define endpoint URLs with query string 

### ISSUE THREAD

**Issue by sunkaiqin** [onelogin/java-saml#212]
Quoted from @comepasto in Issue 126: [SamlResponse validation fails when destination has a query string](https://github.com/onelogin/java-saml/issues/126)

> When I receive the SamlResponse for an AuthnRequest, there are validations made on the 'Destination' and the recipients of a subject confirmation against the current URL. However, this current URL is stripped from its query strings. That makes my responses fail.

In SAML toolkit-php implementation, it uses these code in SAMLResponse class to allow query strings in SP endpoints:
`if not destination.startswith(current_url)`
In toolkit-java, I think we should do the same thing which allows SP developers to define endpoint URLs with query strings.

P.S. I cannot reopen that issue linked in the beginning so I create this new one.

**Comment by sunkaiqin** [comment]
I have created a pull request for this issue, could anyone review it and let me know if there is any change needed?

**Comment by pitbulk** [comment]
[php-saml](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Response.php#L226) uses string comparison, [python-saml](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/response.py#L212) uses startswith.

The standard says the following related to the Destination element:
```
A URI reference indicating the address to which this response has been sent. This is useful to prevent
malicious forwarding of responses to unintended recipients, a protection that is required by some
protocol bindings. If it is present, the actual recipient MUST check that the URI reference identifies the
location at which the message was received. If it does not, the response MUST be discarded.
```
```
If the message is signed, the Destination XML attribute in the root SAML element of the protocol
message MUST contain the URL to which the sender has instructed the user agent to deliver the
message. The recipient MUST then verify that the value matches the location at which the message has
been received.
```

I see that most of SAML implementations uses strict comparison rather than "startswith" approach:
* [KeyCloack](https://github.com/keycloak/keycloak/blob/a8a9631d4fcce744959182436a3a3493e314d1e4/saml-core/src/main/java/org/keycloak/saml/validators/DestinationValidator.java#L99)
* [simpleSAMLphp](https://github.com/simplesamlphp/saml2/blob/0deeebac1efdaee7229f118a18f8b56f40c84569/src/SAML2/Response/Validation/ConstraintValidator/DestinationMatches.php#L42)
* [Shibboleth](https://git.shibboleth.net/view/?p=java-opensaml.git;a=blob;f=src/org/opensaml/saml2/binding/decoding/BaseSAML2MessageDecoder.java;h=0c568631ac8f1fe6070ef775fdf2f19633add9a5;hb=6a793210ab3e0869357f5311cf6f7fee2d15a29a#l387)

so I don't think relax the Destination validation is a good idea.

**Comment by sunkaiqin** [comment]
Thanks @pitbulk  for providing the detailed information and I agree with you we should have strict validations on Destination element for security.

The root cause is when getting the request URL the query strings are discarded. As long as you use query strings in SP endpoints it will always fail for Destination validation. 

Should we include the query strings when retrieving request URL to fix the issue? Otherwise it looks like there is no way to define SP endpoints with query strings.

**Comment by pitbulk** [comment]
Yes, I think query strings should be attached when building the request object used at Auth and SamlResponse classes.

**Comment by sunkaiqin** [comment]
OK, I am going to modify that PR based on the discussion above.

**Comment by pitbulk** [comment]
ty

**Comment by sunkaiqin** [comment]
Investigated more into this issue and below are some findings:

1. HttpRequest is used to hold request URL and query strings. 
2. The request URL is then used to construct SamlRespone, LogoutRequest and LogoutResponse classes. 
3. That request URL (without query string) is used to validate the Destination element.

Here are some challenges:

- For SamlResponse, since it is using POST-binding, we could provide a full request (with query string) to pass destination validation.
- But LogoutRequest and LogoutResponse are both HTTP-Redirect binding which other information will also be included in the URL as query string. This makes it very hard to correctly retrieve the right full request url. 

It looks like there is no good way to support Destination urls with query string. 

@pitbulk Could you share some insight regarding this issue?

**Comment by pitbulk** [comment]
Some threads to review:
- https://stackoverflow.com/q/31132829
- https://stackoverflow.com/q/48966420

**Comment by sunkaiqin** [comment]
Based on the investigation, I think I need a little more time to figure out a better solution for this issue.

**Comment by sunkaiqin** [comment]
Didn't find time to work on it, so closing it for now.
