### ISSUE TITLE
Failures from http://saml.oktadev.com/ "Run security validation"

### ISSUE THREAD

**Issue by wcurrie** [onelogin/java-saml#237]
Forgive me if I'm wrong/misguided/misusing this library. I'm running the "security validation" tests from Okta's test site at http://saml.oktadev.com. I get 2 test cases failing.

![image](https://user-images.githubusercontent.com/2050920/62164674-36da0180-b360-11e9-823f-0e11fd6d03e5.png)

This one looks like it removes `NotOnOrAfter` from the `saml:Conditions` element and expect the receiver to reject the assertion. ie removes `NotOnOrAfter` from:
```xml
<saml:Conditions NotBefore="2019-07-30T06:36:14.911Z" NotOnOrAfter="2019-07-30T07:36:14.911Z">
  <saml:AudienceRestriction>
    <saml:Audience>https://www.blahblahblah.com</saml:Audience>
  </saml:AudienceRestriction>
</saml:Conditions>
```

I can't see anywhere this library checks the timestamps in `saml:Conditions`. The `queryAssertion` in `SamlResponse` is private. Should these timestamps be checked by `onelogin/java-saml`? Could/should the decision at least be left to a client by making `queryAssertion` method public?

![image](https://user-images.githubusercontent.com/2050920/62164687-3f323c80-b360-11e9-900d-262b2e9a1b0c.png)

I can't see a way to parse a deflated/compressed response since `SamlResponse.loadXmlFromBase64` calls `Util.base64decoder` expects an encoded but not deflated response. Perhaps the body of this method could be extracted into a new `loadXmlFromDecoded` or just `loadXml` allowing the caller to deflate if required https://github.com/onelogin/java-saml/blob/9cfea68affc21e40e7ed3304b7e376739e9ec21d/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L126-L141

Perhaps in practice IdPs don't send defaulted `SamlResponse` messages..

I'm happy to raise PRs doing the work if you're happy to accept the changes. I'm also happy to ignore the test failures if you think the test cases are overly enthusiastic but that leaves me wondering "Why do Okta include these test cases in the test suite?"

Thanks for providing a simpler java saml library!

**Comment by pitbulk** [comment]
Times on Conditions are validated here:
https://github.com/onelogin/java-saml/blob/db6c5acdeb855d37272e822f946d9a055da7d7d9/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L926
but the times are validated if present


And it also validates that the Conditions element exists:
https://github.com/onelogin/java-saml/blob/db6c5acdeb855d37272e822f946d9a055da7d7d9/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L619

As well as the audience:
https://github.com/onelogin/java-saml/blob/db6c5acdeb855d37272e822f946d9a055da7d7d9/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L651

Never used that Okta service so not sure exactly why is raising those errors.
Maybe because the toolkit accepts a SAMLResponse with no NotOnOrAfter.

Related to the compress stuff, the toolkit only supports HTTP-POST binding for receiving SAMLResponses, and it expects message only base64encoded.

**Comment by wcurrie** [comment]
> Maybe because the toolkit accepts a SAMLResponse with no NotOnOrAfter.

👍That's what I figured too. Looking at https://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf I see mention of a different element with `NotOnOrAfter`. I can see the toolkit enforcing that one is present.

> The bearer \<SubjectConfirmation> element described above MUST contain a \<SubjectConfirmationData> element that contains a Recipient attribute containing the service provider's assertion consumer service URL and a NotOnOrAfter attribute that limits the window during which the assertion can be delivered....

Can't see any mention of `<Condition>` also requiring `NotOnOrAfter`. I'm just gonna ignore the Okta test case. Seems like the intent of "ensure this assertion has an expiry date" is already covered by `SubjectConfirmationData` 🤷‍♂ 

> inflate/deflate is used only on the HTTP-Redirect binding

Thanks for confirming. Will ignore that case too.
