### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by meeximum** [onelogin/java-saml#261]
Hi,

can I use java-saml as kind of proxy? I mean I have an external IdP (ADFS) and the SP is not the application itself (localhost:8080/java-saml-tookit-jspsample/), but another external URL e.g. https://my.system.com? The SP entity, the ACS and SLO are hosted on my.service.com

regards
Markus

**Comment by sunkaiqin** [comment]
Just curious: why would you use java-saml as a proxy? 

Perhaps you could use Nginx as a proxy for your own SP service which could be easier. 

One thing need to mention though if you are using a proxy you need make sure the SP ACS, SLO urls from SAMLResponses match your service defined ACS, SLO urls after the proxy forwarding. Because these urls will be validated if you turn on "strict validation" in java-saml which you should do.

**Comment by meeximum** [comment]
I have the scenaria (A) Browser (B) Application and C (REST Service)
on B I want to use java-saml to autorize against an IdP (ADFS) and the SP ist not B but C, C is defined as SP trusting the ADFS. On B I want to run independent apps that can consume the REST Services on C.
I was searching all the www like a madman, with no luck, but the I saw the java-saml tutorial and thought maybe this is my missing link :-)

**Comment by sunkaiqin** [comment]
I feel like this setup defeat the purpose or trust relationship of SAML between SP and IdP. The SP metadata will be configured in IdP and IdP will redirect back to SP after authentication. I don't know how could you let C be SP but let B authorize against IdP.

Forgive me if I am wrong :)

**Comment by pitbulk** [comment]
Use SAML between A and B and then OAuth2 between B and C
