### ISSUE TITLE
Remove sha1 from signature whitelist

### ISSUE THREAD

**Issue by amasson88** [onelogin/java-saml#294]
In https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/util/Util.java, `isAlgorithmWhitelisted` contains SHA-1 based signature algos.

There should be a way to remove them from this list (and always reject them) now that SHA-1 is broken.

See https://sha-mbles.github.io/

thanks
Arnaud

**Comment by pitbulk** [comment]
isAlgorithmWhitelisted returns a list of the sign algorithms supported by the toolkit.

The sign is made by the IdP who should use a robust algorithm.

If we remove sha1 from the list, any Signature made with SHA-1 gonna be rejected and maybe some active integrations still using SHA-1 will be broken.

So rather than remove it, maybe we could add a log warning of this fact and control the available allowed alg by a setting.

**Comment by amasson88** [comment]
A new setting to control the list sounds good.
That said, not sure SHA-1 should be enabled _by default_ for someone starting to use the lib.

**Comment by pitbulk** [comment]
@amasson88,

please review https://github.com/onelogin/java-saml/pull/295 and verify this PR works for you.
