### ISSUE TITLE
Does the one login SAML API support sign and then encrypt assertion 

### ISSUE THREAD

**Issue by hairinwind** [onelogin/java-saml#336]
I need to sign the assertion and then encrypt the signed assertion. But I did not find the proper API to do that.

Like this one, https://javadoc.io/static/com.onelogin/java-saml-core/2.4.0/index.html?com/onelogin/saml2/util/Util.html
I only see addSign but no encryption.

Does it support that? Thanks,

**Comment by pitbulk** [comment]
Sign/Encrypt Assertions is a task for an IdP. java-saml implements an SP.

That said, as you saw, the toolkit implements signature on the HTTP-Redirect binding, so a Signature is generated (GET parameter). But also in order to allow provide signed Metadata, there is the addSign method in Utils.java.

The same Utils.java defines a decrypt method, but there is no an encrypt method defined, but toolkit supports NameId encryption:
https://github.com/onelogin/java-saml/blob/1d2b8bc6287e0d7ae19c61923ff20a3146c9a47e/core/src/main/java/com/onelogin/saml2/util/Util.java#L1707
