### ISSUE TITLE
Vulnerability to computed-value attack?

### ISSUE THREAD

**Issue by laurilehmijoki** [onelogin/java-saml#355]
Hi

Is OneLogin Java SAML vulnerable to the computed-value attack described in [this](https://joonas.fi/2021/08/saml-is-insecure-by-design/)  blog post?

**Comment by mauromol** [comment]
I'm not a security expert, but that blog post seems a bit biased to me.
If I understand it correctly, the supposed vulnerability does not lie in SAML libraries (like java-saml) or in SAML itself, but rather in the XML signature. XML signatures are used in a wide variety of scenarios, so it would surprise me if they were really so flawed and easy to break.
The blog post assumes that it's easy to manipulate a XML document so that you get another XML document which is binary different, which still validates against the SAML schema, with the same normalised "structure" (so that it produces the same signature) but carrying an assertion for a different user... I hardly imagine how this could be possible. The JSON example reported there is overly simple and does not help to figure out what could happen in the XML case.
However, as I said, I'm not a security expert.

**Comment by amasson88** [comment]
The source is interesting: https://mattermost.com/blog/securing-xml-implementations-across-the-web.
It seems they can produce (relatively easily) another XML payload having the same signature only because there is a bug in the underlying XML lib ("unstable" roundtrip), which is not rare on various environments.
It's a bit concerning, but they say jdk case is not too bad.

**Comment by laurilehmijoki** [comment]
> The java-saml toolkit was audited several times by 3rd party sec consultant that weren't able to find this kind of vulnerabilities.

Thank you for the reply. Are there public reports of these 3rd party audits?

**Comment by pitbulk** [comment]
They were internal audits
