### ISSUE TITLE
I am using keycloak as Idp and onelogin's saml java toolkit, need example

### ISSUE THREAD

**Issue by lalitmetkar** [onelogin/java-saml#365]
I am using keycloak as Idp and onelogin's saml java toolkit, need example

**Comment by pitbulk** [comment]
I don't get what you need.

In order to integrate them, you need to register KeyCloack IdP metadata into the[ java-saml settings](https://github.com/onelogin/java-saml/blob/master/samples/java-saml-tookit-jspsample/src/main/resources/onelogin.saml.properties).  Then register on KeyCloack the [java-saml metadata](https://github.com/onelogin/java-saml/blob/master/samples/java-saml-tookit-jspsample/src/main/webapp/metadata.jsp)
