### ISSUE TITLE
Asserting request URL and Destination attribute of SAML response fails when working behind load balancer with SSL offload

### ISSUE THREAD

**Issue by jasmdk** [onelogin/java-saml#95]
When the SP consumer URL uses SSL, the client is being redirected to the https endpoint matching the Destination property. Reading the request URL form the servlet request on a server behind a load balancer that does SSL offload the URLs do not match as the request URL is perceived as http not https.
Could this check be configurable to either disable only this check or to choose to disregard the protocol in the comparison?

**Comment by miszobi** [comment]
@jasmdk you should be able to workaround this by configuring your server so that it is aware of the proxy and returns the original url when requested.

For Apache Tomcat this is done by setting the `proxyName`, `proxyPort`, `scheme` and `secure` attributes for the `Connector`. See [here](http://serverfault.com/questions/774300/ssl-offloading-from-apache-to-tomcat-get-overwritten-somewhere) for an example.
